on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        uses: dawidd6/action-get-tag@v1
      - name: install rollup
        run: npm install --global rollup
      - name: install dependencies
        run: npm install
      - name: build
        run: rollup --config
      - name: create GitHub release
        run: |
          mv dist/index.browser.js plugin.js
          gh release create ${{ steps.get_version.outputs.tag }} plugin.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
